### ISSUE TITLE
retroarch ebuild got a lot of issues

### ISSUE THREAD

**Issue by barbudreadmon** [stefan-gr/abendbrot#7]
I did a lot of testing last few days on my raspberry pi, and i noticed a few issues whle trying to build it with correct hardware acceleration support : 
- OpenGLES needs OpenGL to work, retroarch will build fine with OpenGLES and without OpenGL, but you won't be able to select GL acceleration in UI without the later.
- OpenGLES seems to need EGL to build fine.
- EGL don't need X11

i'm also experimenting with some arm-specific configure options, i'll do a pull request of a rpi-ready retroarch ebuild after more testing.

**Comment by stefan-gr** [comment]
Hi, 
* You are right gles needs opengl to work and egl isn't depended on x11.
* I could not reproduce that gles needs egl, it builds fine without egl for me on amd64. Perhaps it's arm specific? If yes then i will add some conditional code to it.

There should be some changes up in the next minutes, can you look into it and tell me if it solves those issues?

I'm looking forward to your arm changes.

**Comment by barbudreadmon** [comment]
I'll give it a try tomorrow (i hope), right now i just received my raspberry 2 and i'm rebuilding the full system with right cflags.

**Comment by barbudreadmon** [comment]
It seems to work, i added some flags for arm specific optimization, they are : 
$(use_enable armvfp floathard) \
$(use_enable neon) \

Feel free to add them yourself since i'm doing a lot of testing on my rpi2 and i don't know when i'll have the time to make a pull request.

**Comment by stefan-gr** [comment]
Alright, thanks for that.
I remember some other libretro cores having specific arm optimization, will look into that when i have my rpi running. Sadly it's the old one so it will take a while.

**Comment by hololeap** [comment]
I am having some similar issues building games-emulation/retroarch-1.3.2 and games-emulation/retroarch-9999-r1 . My system is Gentoo using x86_64-pc-linux-gnu CHOST. It fails with something about not finding the proper EGL functions:

> CC gfx/drivers_context/wayland_ctx.c
> CC input/common/input_x11_common.c
> CC input/drivers/x11_input.c
> Makefile:128: recipe for target 'obj-unix/gfx/drivers_context/wayland_ctx.o' failed
> gfx/drivers_context/wayland_ctx.c: In function 'gfx_ctx_wl_init':
> gfx/drivers_context/wayland_ctx.c:477:17: error: unknown type name 'EGLint'
>     static const EGLint egl_attribs_gl[] = {
>                  ^
> gfx/drivers_context/wayland_ctx.c:478:7: error: 'WL_EGL_ATTRIBS_BASE' undeclared (first use in this function)
>        WL_EGL_ATTRIBS_BASE,
>        ^
> gfx/drivers_context/wayland_ctx.c:478:7: note: each undeclared identifier is reported only once for each function it appears in
> gfx/drivers_context/wayland_ctx.c:479:7: error: 'EGL_RENDERABLE_TYPE' undeclared (first use in this function)
>        EGL_RENDERABLE_TYPE, EGL_OPENGL_BIT,
>        ^
> gfx/drivers_context/wayland_ctx.c:479:28: error: 'EGL_OPENGL_BIT' undeclared (first use in this function)
>        EGL_RENDERABLE_TYPE, EGL_OPENGL_BIT,
>                             ^
> gfx/drivers_context/wayland_ctx.c:480:7: error: 'EGL_NONE' undeclared (first use in this function)
>        EGL_NONE,
> !!! emake returned error 2
> 
> !!! Call stack:
> !!!    * paludis_die_or_error_func (/usr/libexec/paludis/die_functions.bash:82)
> !!!    * main (/usr/libexec/paludis/utils/emake:30)
> 
> diefunc: making ebuild PID 24629 exit with error
> die trap: exiting with error.
> 
> Failed install to / for games-emulation/retroarch-9999-r1:0::abendbrot

I have media-libs/mesa installed with the gles2 flag enabled and here are my enabled use flags for retroarch:

>     Use flags                 
>         USE                   
>             alsa              Enable ALSA support
>             (-armvfp)         Enable Vector Floating Point (VFP) instruction set support for post-ARMv5 ARM architectures
>             assets            adds games-emulation/retroarch-assets as dependency
>             cg                Enable Cg shader support
>             -cheevos          Enable Archievment support via http://retroachievements.org/
>             cores             Changes default retroarch.cfg to the standardpath of the libretro* ebuilds
>             database          adds games-emulation/libretro-database as dependency
>             -egl              Enable EGL context support
>             fbo               Enable render-to-texture (FBO) support
>             -ffmpeg           Enable FFmpeg recording support
>             -gles2            Use GLESv2 instead of OpenGL
>             -gles3            Enable OpenGLES3 support
>             -jack             Enable JACK support
>             joypad_autoconfig adds games-emulation/retroarch-joypad-autoconfig as dependency
>             -kms              Enable KMS context support
>             -libusb           Enable Libusb support
>             materialui        Enable materialui menu (named glui in driver selevtion)
>             (-neon)           Enable optimization support for ARM NEON processors
>             netplay           Enable netplay support
>             network           Enable network support (recommended)
>             -openal           Enable OpenAL support
>             opengl            Enable OpenGL support
>             -oss              Enable OSS support
>             overlays          adds games-emulation/common-overlays as dependency
>             -pulseaudio       Enable PulseAudio support
>             -python           Enable Python 3 support for shaders
>             sdl               SDL support
>             -sdl2             SDL2 support
>             shaders           adds games-emulation/common-shaders as dependency
>             threads           Threading support
>             truetype          Enable FreeType support
>             udev              Udev/Evdev gamepad support
>             -v4l2             Enable video4linux2 support
>             x11               Enable x11 support
>             xinerama          Enable Xinerama support
>             xmb               Enable xmb menu
>             xml               Enable libxml2 support
>             xv                Enable XVideo support
>             zlib              Enable zlib support (ZIP extract, PNG decoding/encoding)
>         python_single_target  
>             -python3_3        Build for Python 3.3 only
>             python3_4         Build for Python 3.4 only
>         python_targets        
>             -python3_3        Build with Python 3.3
>             python3_4         Build with Python 3.4
> 

Any ideas on how to get it to compile? I just want a basic setup that can play SNES games...

**Comment by leycec** [comment]
> I just want a basic setup that can play SNES games...

I feel your pain. Retroarch isn't the simplest package to get going, but when it does... _oh, boy._ Sheer awesome-sauce.

Thanks for the detailed issue report, as well. A few things immediately standout:

1. **You're installing the live unstable developer version of `retroarch`.** Since you only require SNES support, however, you might consider installing stable releases of `retroarch` instead. [Stefan](https://github.com/stefan-gr) recently bumped `retroarch` to [1.3.2](https://github.com/stefan-gr/abendbrot/blob/master/games-emulation/retroarch/retroarch-1.3.2.ebuild), which would probably serve you just as well (if not better) than the live unstable developer version.
1. **We need to add a `wayland` USE flag to `retroarch`.** As you have the existing `x11` USE flag enabled, it seems unlikely that you actually want Wayland functionality – which appears to be the source of your compilation woes. It's likely that upstream recently added Wayland support. We failed to notice. <sup>_Sorry about that._</sup>
1. **Wayland support appears to require EGL support.** However, you have the `egl` USE flag disabled. All of the error messages pertain directly to both Wayland and EGL: e.g.,

```
gfx/drivers_context/wayland_ctx.c:477:17: error: unknown type name 'EGLint'
gfx/drivers_context/wayland_ctx.c:478:7: error: 'WL_EGL_ATTRIBS_BASE' undeclared (first use in this function)
gfx/drivers_context/wayland_ctx.c:479:7: error: 'EGL_RENDERABLE_TYPE' undeclared (first use in this function)
gfx/drivers_context/wayland_ctx.c:479:28: error: 'EGL_OPENGL_BIT' undeclared (first use in this function)
gfx/drivers_context/wayland_ctx.c:480:7: error: 'EGL_NONE' undeclared (first use in this function)
```

As a temporary fix on your side, hololeap, would you mind temporarily enabling the `egl` USE flag for this ebuild, downgrading to `retroarch-1.3.2` (or possibly even `retroarch-1.3.1` or `retroarch-1.2.2`) and trying again?

In the meanwhile, we'll try to address this from our end as well. Thanks again for the detailed report. I hope we eventually get you sorted out. RetroArch is worth it! :no_mouth:

**Comment by leycec** [comment]
@hololeap In theory, this should be fixed now. A new `wayland` USE flag has been added to the ebuild. Since Retroarch's Wayland implementation appears to be broken for common use cases (e.g., when the `egl` USE flag is disabled), adding the following line to your `/etc/portage/package.use` _should_ solve this issue for you – in theory:

    games-emulation/retroarch -wayland

Would you mind `sync`-ing and retrying? I don't have Wayland locally installed and would rather _not_ install Wayland merely to test this, so I'm afraid you're our reluctant code guinea pig! :pig:

**Comment by leycec** [comment]
@stefan-gr I magically discovered free time this weekend. Thanks to that, I've heavily revised our front-facing `README.md` _and_ RetroArch USE flags. Feel free to hack everything I've done into little bloody pieces.

Have a fun-filled Sunday evening of stomache-plumping abendbrot! :bread: :tea:

**Comment by stefan-gr** [comment]
@leycec @hololeap It should work now. I tried with and without the wayland backend and it builds and works just fine. I missed that due to global egl flag.

@leycec Thanks for writing the first proper frontpage.
